### ISSUE TITLE
Bug on mach+WEP on poursuit view

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#172]
Hi @Uchuujin01 
Can you watch from 1'40", when I'm behind another plane at more mach, there is some kind of sound bug on the WEP and I can't find where the problem comes from

https://youtu.be/ohjezPyZ-Zw?t=103

Thanks in advance
Best reagrds

**Comment by Uchuujin01** [comment]
Hello! Sorry for my missing for significant time.

Do you experiencing this on both vanilla modified game? Maybe it is lack of refresh rate of sound position, I'll mark this up, thank you.

**Comment by IWSM** [comment]
> Hello! Sorry for my missing for significant time.
> 
> Do you experiencing this on both vanilla modified game? Maybe it is lack of refresh rate of sound position, I'll mark this up, thank you.

No problem @Uchuujin01 

yes, this also happens, without the mod.  it is as if the two positions burns on top of each other, causing a sound bug.

**Comment by IWSM** [comment]
I don't have a problem with tanks personally, only in the situation explained at the beginning

**Comment by Uchuujin01** [comment]
@OXEPU3M I definitely don't experience such problem, and I have no similar reports about ground vehicles engines sound bugs. Anyway, this problem here is not the same as on video with jets, it is about refresh rate, it is slower that the speed of an aircraft. We still investigating this problem, we just can't increase the refresh rate because of game performance.

**Comment by IWSM** [comment]
I doubt it.  Thank you very much for the clarification. I haven't seen this problem on tanks either.
