### ISSUE TITLE
Autoloaders again

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#184]
Здравствуйте.
Порадовали поправками с ивентами перезарядок танков.
Есть, правда, ещё ряд машин с автоматами и неправильными ивентами. Будем благодарны, если выделите время на исправление. Совсем хорошо, если успеете до обновления репозитория, тогда можно будет сотворить что-нибудь красивое.

К сожалению нет возможности прокатать всю технику игры из-за политики разработчика. Могу на всякий случай приложить список всех машин (из доступных в клиенте) с мехаизированной боеукладкой и автоматами заряжания.

**США:**
XM-8
AGS
M1128 (2ШТ)
CCVL
MBT-70
XM-803
KPz-70

**Германия:**
Turm III
VT1-2
PT-16/T14 mod.
DF105
JzPz.K A2

**СССР:**
Объект 120
ИС-7 (Спорно. Обозначен как автомат заряжания. Но в конструкции танк вроде бы использовали досылатель и двух молодчиков для картузного заряжания. Не знаю, как в логике игры это отражено.)

**В.Британия:**
Rooikat MTTD

**Япония:**
Type 90
Type 90 (B)
TKX
Type 10

**Китай:**
ZBD86
PTZ89
Танки ZTZ96+ и WZ1001 используют ивент зарядки от Т-64, верно?

**Италия:**
VCC-80/60

**Франция:**
На всякий случай
AMX M4
Somua SM
AMX-50 (TOA100)
AMX-50 Surblinde
AMX-50 Surbaisse
M4A1 (FL10)
Lorraine 40t

**Швеция:**
Bkan 1C
Серия STRV-103 (работают правильно)
CV90105
CV90120

Спасибо за вашу работу.

**Comment by Gentlespie** [comment]
Hello, I have some input on IS-7 autoloader and I believe it should be a unique sound. It actually used electric motors to drive itself completely and since I have the detailed loading process here, you could use it to make a unique sound event for it! [Image 1](https://media.discordapp.net/attachments/593204578372288530/1085685746721112145/20230315_224550.jpg?width=662&height=883) [Image 2](https://media.discordapp.net/attachments/593204578372288530/1085685747241201694/20230315_224556.jpg?width=662&height=883)

**Comment by OXEPU3M** [comment]
Здравствуйте ещё раз.
В коде игры закралась ошибка. AMX-13 (FL11) использует звук автоматического заряжания.
