### ISSUE TITLE
T-34 and F-104 missing sounds

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#23]
I've working on a Soundmod that mostly contains the old Gun sounds of War Thunder . I only use 
masterbank.bank
masterbank.strings.bank
tank_effects.bank  (for the old bounce/ricochet sounds)
tank_weapons.bank

Since some small updates/changelogs, the T-34 series missing his engine sound completely
and the F-104 also misses his engine sounds including the new M61 cannon sounds

I also had a same issue with all MG sounds like a week ago but it was fixed with an small War Thunder update somehow. 
I use the FMOD version 1.10.17

**Comment by Uchuujin01** [comment]
Hello! Yes, that is because F-104 and T-34 sounds are not exist in current version of fmod project for modders. So, even if they exist in default game sound banks, they're absent in your custom masterbank.strings.bank.

I hope soon we will release new project version, in about week or two. I'm not sure about release date because we're just switched on new Fmod Studio 2.00.09, so it needs some tests first. If we will find some problems, release date might be delayed.

**Comment by Uchuujin01** [comment]
Hello! The project has been updated. Now it needs Fmod Studio 2.00.09.
