### ISSUE TITLE
Update when?

### ISSUE THREAD

**Issue by Anitname** [GaijinEntertainment/fmod_studio_warthunder_for_modders#45]
I need to know pls, AI tanks have no sound.

**Comment by RadonSound** [comment]
i would rather have the current version fixed than a new project. 
i dont really want to do all over again. *adjust every single impact and every single caliber sound flashbacks*
+ i opened a kinda same issue report already

**Comment by Uchuujin01** [comment]
Hello! I'm about to prepare an update next week, because now I need to fix some issues that become obvious after the major release.
"i would rather have the current version fixed than a new project." - I'm not sure I understand you. What's the difference between fixing the current version and a prepeariong a new one?

**Comment by Uchuujin01** [comment]
"AI tanks have no sound." - now we have a unique engone sounds for the AI tanks. So, you can add a new folder in ground/engines/, call it "ai". So, it will be ground/engines/ai. Now you can copy all your engines from ground/engines/, BUT, don't forget to simplify it. I recommend to leave only one layer of sounds (rpm layout, "load" assets), and one for loadswitch. And one for "broken" engine state. And, add some processing for distance, now the distance is 300 m.

**Comment by Anitname** [comment]
Thanks for the tip/reply! @Uchuujin01
