### ISSUE TITLE
Bugs with ai armor hits

### ISSUE THREAD

**Issue by 787992** [GaijinEntertainment/fmod_studio_warthunder_for_modders#49]
Hello again,

I edited a bit newly added events but there's small problems here and there:
1) Plase take a look how it works overall, i tested several times with friend (that was shooting bots), ai hits works differently then player one.
50% case of obvious ricochets are not working - playing unpierce instead, ricochets events for apfsds are 100% not working.
2) Might be a bug, but i setup all distances up to 1km (with restriction) but sometimes i hear hits from plane when flying above battlefield (ground rb) nearly 3km above, so there's something weird.
3) Little suggestions to make ai hits from 20mm to 35mm, currently playing hit_small which a little bit overkill for such calibre, it also shares with all low caliber cannons same like planes and stuff
4) I think now can be used atgm_hit sounds instead of wreck_explosion that was initially intended for planes.

Non-related: i see all small he shells now using proper explosion sound, while for guns like 600rpm or lower pretty much okay (it matches with rpm) guns like ADEN or M61 with high rpm really asking for "Ziiip" explosion effects, one time explosion might be overkill, maybe some kind of loop sfx?

**Comment by Uchuujin01** [comment]
"Plase take a look how it works overall, i tested several times with friend (that was shooting bots), ai hits works differently then player one.
50% case of obvious ricochets are not working - playing unpierce instead, ricochets events for apfsds are 100% not working." - Hello! I'm not sure I understood, did you mean sound events doesn't work? Or in-game mechanic of ai hits?

"Might be a bug, but i setup all distances up to 1km (with restriction) but sometimes i hear hits from plane when flying above battlefield (ground rb) nearly 3km above, so there's something weird." - Yes, this is definitely wrong vehaviour. But, it doesn't seem what in game it works wrong now.

"Little suggestions to make ai hits from 20mm to 35mm, currently playing hit_small which a little bit overkill for such calibre, it also shares with all low caliber cannons same like planes and stuff" - yes, probably, I'll check it, thank you.

"I think now can be used atgm_hit sounds instead of wreck_explosion that was initially intended for planes." - yes, it should be atgm_hit for ATGMs, what do you mean, explain please.

**Comment by 787992** [comment]
> Hello! I'm not sure I understood, did you mean sound events doesn't work? Or in-game mechanic of ai hits?

Yea, how it works in game, some events are not matching what actually happens, noticed that pretty often instead of ricochet playing unpierce event.

> But, it doesn't seem what in game it works wrong now.
Sure nothing wrong with vanilla, but with cutom increased distance, happenes what i mentioned above, I will try to record a video for that.

> yes, it should be atgm_hit for ATGMs, what do you mean, explain please.
Oh sorry, i meant for ai hits too. Currently it uses wreck_explosion for tank atgm hit

**Comment by Uchuujin01** [comment]
"Yea, how it works in game, some events are not matching what actually happens, noticed that pretty often instead of ricochet playing unpierce event." - I'm not sure about it, recently we worked on ai hit effects - it did not notice any difference between what I saw and what my colleague saw - we both saw same effects (rico or hits).
"Sure nothing wrong with vanilla, but with cutom increased distance, happenes what i mentioned above, I will try to record a video for that." - I'm not sure now what can be a problem, It is definitely needs some investigation.
"Oh sorry, i meant for ai hits too. Currently it uses wreck_explosion for tank atgm hit" - It is wrong, I'll check it, thank you!

**Comment by 787992** [comment]
> it did not notice any difference between what I saw and what my colleague saw - we both saw same effects (rico or hits).

Alright i did a little bit investigation. In most part ai hits works as intended but there's some stuff that needs more attention.
Hit like big, mid and small everything works as intended but there's plenty situations where sound does not match the actual hit.

So, i found 2 questionable things:
1.Generic hits (Big, mid, small).
2.All unpierce events.

1.I'm a bit confused by these generic hits, when 85mm non pens with aphe, hit_mid playing, same with 122mn aphe.
99% of time playing generic hit events only when you non-penning target with any type of shell (aphe, he, heat)

But here comes the opposide situation when sharpnel hits mg port and thus damaging mg itself - playing hit_mid_aphe or hit_big_aphe but still did not penned armor.

From everything above comes second conclusion:
2.It's almost impossible to get unpierce events - playing generic hits or in very rare cases penned armor event

Exactly same working for ricochets, if ricochet damaged track same stuff happens. (obvious ricohets working as intened too)

**Comment by Uchuujin01** [comment]
I didn't know about this issues, we'll check them more carefully. It is amazing that we can get help such yours. It is always a problem, when you deal with a big projects - to pay enough attention to details, even if they important. Thank you for your investigation, appreciate it!

**Comment by 787992** [comment]
> Thank you for your investigation, appreciate it!

Guess i should thank you for making more amazing features each update.

Regarding hits that can be heard from space, yea i figured how. So it happens only when you are in plane (ground rb for example), system completely ignoring distance restrictions, even min-max one.
Not really sure how and why it is not the same with vanilla, i'll try again with completely clean project.

**Comment by Uchuujin01** [comment]
Understood, maybe it is some kind of speciefic sound event that was made only for player vehicle use, but was used for AI vehicle effects somehow. I'll check it.

**Comment by 787992** [comment]
> Understood, maybe it is some kind of speciefic sound event that was made only for player vehicle use, but was used for AI vehicle effects somehow. I'll check it.

Fixed it, weird stuff, i just re-created audio layers, parameters and spatializers, probably somthed bugged out after porting new events.

**Comment by Uchuujin01** [comment]
Yes, probably. Maybe, wrong position in Mixer view hierarchy?
