### ISSUE TITLE
Patchnote Question

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#69]
Hello,

I've read the Patchnote on the new project and it says
"PS: hangar.bank still contains music events, that's bad news. But, I'm about to get rid of it in the next major update."
does this mean when a new major update drops, we have to make a whole new project?

Is it actually possible to update projects by myself? like when new sounds or sound sound mechanics are added, to simply kinda drag and drop , instead of making a new project. Ive done this one time with the update New Power but the problem there was, there where just too many things some even impossible for me to drag and drop (like the new music banks)
So will there ever be a final and stable project that allows to simply drag 'n drop new things without any complications?

The current one i have got killed with the last ingame majorpatch. means, bombs and arty impacts are completly muted and tank hit effects are unstable for some reason (sometimes they play sometimes not) . I dont know why that happend

**Comment by Uchuujin01** [comment]
"does this mean when a new major update drops, we have to make a whole new project?" - no, it means only that you'll get less troubles. Because of music sound events it contains, for example.

"Is it actually possible to update projects by myself? like when new sounds or sound sound mechanics are added, to simply kinda drag and drop , instead of making a new project. Ive done this one time with the update New Power but the problem there was, there where just too many things some even impossible for me to drag and drop (like the new music banks)
So will there ever be a final and stable project that allows to simply drag 'n drop new things without any complications?"

Exuse me, I don't understand. Why can't you drag'n'drop? Maybe it is because of fmod versions transition? You can drag'n'drop, if fmod studio versions is the same. It is normal that you can't drag'n'drop, for example, form 2.0.9 to 2.1.6.

Anyway, the game evolves constantly, hope you understand that it is impossible to freeze the project in one state.

**Comment by RadonSound** [comment]
Im sorry i have trouble to ask this correctly :(
Im wondering how this works then. The new project still has the hangar.bank and the next patch don't . How will the transition be? like do i still have to build the hangar.bank in fmod when i use the project from today? And when i want to get rid of this bank, i have to get a newer project after a major patch (but the current one from today will still work)?
Im sorry if this sounds super confusing. im not really smart when come about new updates and projects:(

**Comment by Uchuujin01** [comment]
Hello! hangar.bank file will be splitted on several banks, maybe it's content will be spreaded between already existing banks. You can split your hangar.bank content in your project according to the new project bancs. It will take some time but not significant.

Also, we can notify you and other modders about new bank names, so you will be prepared to major update.
