### ISSUE TITLE
Music events?

### ISSUE THREAD

**Issue by wwwWolfcom** [GaijinEntertainment/fmod_studio_warthunder_for_modders#8]
When this repo gonna add existing war thunder Music events(or empty music events) ?

I really want to make old theme mod XD

**Comment by diVineProportion** [comment]
#4

**Comment by Uchuujin01** [comment]
Hello! Empty music events, and crew dialogs, will be in this repo with one of the big major game updates, but I cant say for sure, in which one.

**Comment by Avarik** [comment]
Hey there!

It's great to know you will be adding music events and crew dialogues, however I do want to ask if it's possible to include dialogues and speech events from the tutorial and historical campaign missions for use in singleplayer based sound mods.

I'm asking for this because currently the playSound action in the mission editor doesn't seem to work, so using any event just to play a modded sound with that method is not possible, but it could be done easier with dialogues and speeches using the missionPlayDialogue.

**Comment by diVineProportion** [comment]
This actually brings up something I wanted to ask about.

Correct me if I am wrong, but I believe this means we have to replace an existing event. 

For example if I wanted to include sounds for a custom vehicle I've been working on I have to pick an existing sound event (say engine05) and replace the sounds in there?

Are we going to be able to create our own events and reference them in our cutom CDK vehicles?

**Comment by Uchuujin01** [comment]
> This actually brings up something I wanted to ask about.
> 
> Correct me if I am wrong, but I believe this means we have to replace an existing event.
> 
> For example if I wanted to include sounds for a custom vehicle I've been working on I have to pick an existing sound event (say engine05) and replace the sounds in there?
> 
> Are we going to be able to create our own events and reference them in our cutom CDK vehicles?

Hello! Sorry, I missed out your question ( No, it is impossible to create new events, it is possible to replace existing ones only.
