### ISSUE TITLE
remove "engine" event to leo1 problem

### ISSUE THREAD

**Issue by MathMilitary** [GaijinEntertainment/fmod_studio_warthunder_for_modders#85]
Hi,
I remove leo1 event engine. If replace, not work ingame! what problem please?

**Comment by Uchuujin01** [comment]
Hello! Be sure you've added it into tank_engines.bank, and it belongs to proper bus in mixing deck.

**Comment by MathMilitary** [comment]
Hi, is good for tank_engines.bank. how to see for the bus?

**Comment by RadonSound** [comment]
Im not sure if im correct, but i think that means that the event in mixing desk, must belong into the correct engine bus/grp. 
![Screenshot (400)](https://user-images.githubusercontent.com/67481432/130261259-19a86f2a-aece-4853-8d02-fd4a2bf51622.png)

**Comment by MathMilitary** [comment]
Ok, I look this. Big thanks 🙏

**Comment by RadonSound** [comment]
There are 2 options to open the Mixing desk

![Screenshot (403)](https://user-images.githubusercontent.com/67481432/130307567-41929108-5761-4849-9ac8-fd9cc648d401.png)
![Screenshot (405)](https://user-images.githubusercontent.com/67481432/130307569-a65f4e7c-2ee6-4d0e-ba0b-64f28fcf1597.png)

By right click the Leo1 Engine event and open "Open Even in>New Mixer" , it leads you automatically to the event in Mixer. So you can check where it is and belongs (it works with drag 'n drop). 

1 Year ago, i had a similar problem, where i copy&pasted some events from one project into another. Then i saw (with help) that in Mixer, all the new events where not in the correct Grp's 

But still, I would wait for @Uchuujin01    ,if thats what he means with the buses. because im not 100% sure.

**Comment by MathMilitary** [comment]
Oh yes, ok I chek this now. Big thanks

**Comment by Uchuujin01** [comment]
@RadonSound thank you for the help!

**Comment by MathMilitary** [comment]
Thanks all, is good now 😉
