### ISSUE TITLE
New events with the Patch?

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#90]
Hello,

I would like to know if there are any new events that can be added in the current project. together with the correct banks.

Here are some problems i currently have since Direct Hit

-Arty impacts/explosions are muted
-Aircraft Gun sounds are muted (mentioned already)  (tank mg sounds are working fine)
-For some reason, tanks AI Bump sounds are random played. means sometimes the sounds plays and somtimes not.

Haven't tested everything but still thanks for any advice

**Comment by Uchuujin01** [comment]
Hello! Yes, there are some new events, for some weapon and aircraft/ground engines. I think it's better to release the project update rather to list them here, I'm afraid I can miss something, there are quite many of them.

Regarding aircraft/ground automatic weapon, please check the neighboring topic. THere are a couple of variables for config.blk to switch weapon sound generating modes.

Regarding explosions, there are a new machanism of mass distruction sounds, quite similar to automatic weapon. Instead of spawning a new event every time explosion happens, we pan use the same event but with trigger parameter, we just ned to replace it in 3D space. You'll see it after the project update. I hope it will be soon, maybe next week. We need to consider the project as stable.
